### ISSUE TITLE
Placeholder attribute required for autocomplete query

### ISSUE THREAD

**Issue by linxOD** [BCDH/TEI-Completer#5]
My config:

```XML
<?xml version="1.0" encoding="UTF-8"?>
<config xmlns="http://humanistika.org/ns/tei-completer">
    <server>
        <baseUrl>https://some-endoint</baseUrl>
    </server>
    <autoComplete>
        <context>//rs</context>
        <attribute>@ref</attribute>
        <dependent default="person">@type</dependent>
        <selection>@n</selection>
        <request>
            <url>$baseUrl/$dependent?q=$selection</url>
        </request>
    </autoComplete>
</config>
```
In this example `selection` uses @n as placeholder for the search query. 
The `text()` method usually does not apply since the text varies from the required search query. 
The initial plan was to use @ref for the query in `selection` with the desired outcome that I can overwrite @ref value with autocomplete proposals. Unfortunately this does not work.

Is there another way besides using `text()` or a placeholder attribute?

**Comment by adamretter** [comment]
Sorry... I am not quite sure what you mean by `The text() method`?

**Comment by dasch124** [comment]
Let me try to reformulate @linxOD's question (and please, Daniel, let me know, if I don't got it right):

In many cases the query string which we want to pass to the webservice is not present in the source document (e.g. because it's an indirect mention of a person or a name spelled differently than in the webservice), thus we need  users to input the search string in some place. Daniel currently uses a dummy attribute `@n` for capturing the user input and stores the user selection in `@ref` – which is a bit of a makeshift since those need to be removed afterwards. 
As far as I understand it, the question is whether  there's a more elegant way of collecting user input: e.g. have users input the initial query string into the attribute which will be used to store the final value (`@ref` in the example) or maybe without actually touching the input document in the first place.

**Comment by ttasovac** [comment]
Ok, I think I get it now.

When we created TEI Completer, my primary use case was morphosyntactic tagging and linking places and names to prosopograhies. I did not need, at the time, coreference resolution, but that is actually a very common use case and I agree that we need a solution for it. 

Elegance is in the eyes of the beholder, but for me personally an "elegant" solution would look like this:

1.  we leave things as is for explicit string matching with $selection and $dependency —  that works well for simpler use cases 
2. we introduce an option where a configurable user shortcut creates a small pop-up panel with a search field to allow the user to explicitly search for an entry in the db

For instance, let's imagine you have `<rs>former chancellor</rs>` in your text and you want to link it to 'Angela Merkel', you could place your cursor inside `<rs></rs>`, press the shortcut, get the panel up and search for "Angela Merkel", get a list of matches in a dropdown, select the one that makes sense and then the id attribute will be copied to the `<rs>` as per your configuration.

I think this is what @linxOD had in mind, and I would be very happy if we went for something like this, because this would make our plugins much more versatile.

**Comment by linxOD** [comment]
@adamretter, @ttasovac thank you for you replies. With text() method I meant the xpath funciton text(). But this was already clarified. The proposal for a search input panel would be a great idea. My idea might have been much simpler. I simply wanted to use the e.g. @ref attribute to type the search query as well as reiceve the proposed e.g. xml:id references. Something like an autocomplete search function usually works.

**Comment by ttasovac** [comment]
here too, the new version will support custom lookups...
